# Generated by Django 5.0.2 on 2024-02-19 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                (
                    'main_photo',
                    models.ImageField(upload_to='project_photos', verbose_name='Главное Фото'),
                ),
                ('description', models.TextField(max_length=4000, verbose_name='Описание')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
                ),
                ('url', models.URLField(verbose_name='Ссылка на проект')),
            ],
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('price_rub', models.IntegerField(verbose_name='Цена')),
                ('main_photo', models.ImageField(upload_to='', verbose_name='Главное Фото')),
                ('description', models.TextField(max_length=4000, verbose_name='Описание')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TextBookPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='text_book_photos')),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='goods.textbook',
                        verbose_name='Пособие',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeUrl',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                (
                    'books',
                    models.ManyToManyField(
                        related_name='youtube_urls', to='goods.textbook', verbose_name='Пособия'
                    ),
                ),
                (
                    'projects',
                    models.ManyToManyField(
                        related_name='youtube_urls', to='goods.project', verbose_name='Проекты'
                    ),
                ),
            ],
        ),
    ]
